### ISSUE TITLE
the modal does not close when touch back

### ISSUE THREAD

**Issue by HankTech** [MinaSamir11/react-native-swipe-modal-up-down#2]
Is there a way to close the modal that is not only with swipe?

**Comment by hakimscode** [comment]
i'm having the same issue, did you find how to solve it? @HankTech

**Comment by drbarazi** [comment]
@HankTech @MinaSamir11  hope this PR can help  #3

**Comment by MinaSamir11** [comment]
PR merged, now update package to v1.1.0

**Comment by MinaSamir11** [comment]
@drbarazi  **Thank you**
